version: "2"
services:
  caroline:
    build: .
    working_dir: /home/app
    ports:
      - "80:8080"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=8080
      - WIT_TOKEN=${WIT_TOKEN}
    command: "npm start"
